export class Digit {
    constructor(
        public readonly number: number,
        public readonly panels: Set<string>
    ) {}

    get count(): number {
        return this.panels.size;
    }
}

export const Digits = new Map<number, Digit>(
    [
        new Digit(0, new Set('abcefg'.split(''))),
        new Digit(1, new Set('cf'.split(''))),
        new Digit(2, new Set('acdeg'.split(''))),
        new Digit(3, new Set('acdfg'.split(''))),
        new Digit(4, new Set('bcdf'.split(''))),
        new Digit(5, new Set('abdfg'.split(''))),
        new Digit(6, new Set('abdefg'.split(''))),
        new Digit(7, new Set('acf'.split(''))),
        new Digit(8, new Set('abcdefg'.split(''))),
        new Digit(9, new Set('abcdfg'.split(''))),
    ].map<[number, Digit]>((d) => [d.number, d])
);

export const input8 = [
    {
        input: [
            'ecfdbg',
            'decfba',
            'aegd',
            'fdcag',
            'fagecd',
            'gd',
            'gcafb',
            'efdac',
            'cbgeafd',
            'dfg',
        ],
        output: ['bgacf', 'afdebc', 'fceda', 'cabfg'],
    },
    {
        input: [
            'cfdabeg',
            'cda',
            'bcgad',
            'bedfac',
            'aefbgd',
            'bfgcad',
            'dfbga',
            'egabc',
            'dgfc',
            'cd',
        ],
        output: ['gdbefac', 'fgabcd', 'dcbefag', 'aedgfb'],
    },
    {
        input: [
            'aedbfgc',
            'gcaf',
            'ebgfca',
            'bca',
            'edgcfb',
            'adbge',
            'gebac',
            'fbegc',
            'ac',
            'afdcbe',
        ],
        output: ['ceafbg', 'acb', 'egbad', 'gfaebc'],
    },
    {
        input: [
            'gaeb',
            'cafdbg',
            'aedfc',
            'ecfgdb',
            'ab',
            'cdaefgb',
            'cgbdae',
            'bdecg',
            'cba',
            'eacdb',
        ],
        output: ['gfacdeb', 'gabdec', 'begcd', 'adbce'],
    },
    {
        input: [
            'fcbgea',
            'fbedg',
            'bc',
            'cbefg',
            'befgcda',
            'cfgdab',
            'gbc',
            'efdgca',
            'fecag',
            'aceb',
        ],
        output: ['faecg', 'cb', 'cb', 'fecbga'],
    },
    {
        input: [
            'fdebcg',
            'bag',
            'gdefa',
            'ceadgb',
            'fcab',
            'ebagfc',
            'ab',
            'fbegc',
            'fcaedbg',
            'fbeag',
        ],
        output: ['cfegb', 'bga', 'edfga', 'fgbec'],
    },
    {
        input: [
            'fg',
            'fcagb',
            'dfgceba',
            'edgacb',
            'fagd',
            'gfb',
            'dcgba',
            'agcfdb',
            'gecfbd',
            'ceafb',
        ],
        output: ['facgb', 'fbdcge', 'gf', 'gfabc'],
    },
    {
        input: [
            'eabfd',
            'dfb',
            'gbcfad',
            'ebdag',
            'fagbce',
            'gefabdc',
            'edcf',
            'aecfb',
            'cbdafe',
            'df',
        ],
        output: ['egbcdfa', 'afdebcg', 'aecfbd', 'acefb'],
    },
    {
        input: [
            'fbaec',
            'bfegad',
            'bga',
            'deacbg',
            'gb',
            'fbdg',
            'acgdef',
            'deagf',
            'fgabe',
            'gabecdf',
        ],
        output: ['fgdb', 'gefba', 'gcdafe', 'bg'],
    },
    {
        input: [
            'bfdea',
            'agfbc',
            'gbd',
            'faecdbg',
            'gd',
            'efgd',
            'cdgeab',
            'efadbg',
            'faebcd',
            'fabdg',
        ],
        output: ['cdbgea', 'fged', 'cfabed', 'bgd'],
    },
    {
        input: [
            'gfedac',
            'cgaef',
            'gab',
            'ceba',
            'ba',
            'afcdgb',
            'gdefbac',
            'fegbd',
            'bafeg',
            'abcgfe',
        ],
        output: ['gcbadf', 'egafb', 'ebafg', 'ab'],
    },
    {
        input: [
            'bgda',
            'agfcdbe',
            'agfde',
            'faegb',
            'baedgf',
            'fcdaeg',
            'fdbeac',
            'ba',
            'bcegf',
            'bfa',
        ],
        output: ['bcefg', 'eagdf', 'ab', 'bacefd'],
    },
    {
        input: [
            'dfgbac',
            'fdcaeb',
            'cbgeda',
            'bfdea',
            'dcabf',
            'ebadcfg',
            'gfbea',
            'dbe',
            'fecd',
            'ed',
        ],
        output: ['ebd', 'cdfe', 'bgeaf', 'cdbfea'],
    },
    {
        input: [
            'efdba',
            'edb',
            'eagbcd',
            'bacef',
            'bd',
            'bcfd',
            'becfagd',
            'begcaf',
            'cbaefd',
            'aefdg',
        ],
        output: ['fdage', 'edbgac', 'cgaebd', 'bed'],
    },
    {
        input: [
            'gfecbd',
            'gbadf',
            'fabged',
            'gbf',
            'cbdage',
            'fagcd',
            'feab',
            'edgcbaf',
            'fb',
            'aedbg',
        ],
        output: ['agdcf', 'bgfda', 'afdgc', 'afdgb'],
    },
    {
        input: [
            'gfaedc',
            'caefb',
            'badcfge',
            'dgfe',
            'acdgbf',
            'eag',
            'eg',
            'fgacd',
            'gecfa',
            'ecbdag',
        ],
        output: ['acdbgf', 'cbegad', 'cgdaf', 'eag'],
    },
    {
        input: [
            'gfebda',
            'fgacd',
            'dfbag',
            'bg',
            'geab',
            'gcbdeaf',
            'eacbdf',
            'cedbgf',
            'fbg',
            'abfed',
        ],
        output: ['aedfb', 'gb', 'eafdb', 'dbafe'],
    },
    {
        input: [
            'ebadfc',
            'efdbga',
            'bega',
            'fdgcae',
            'dbgaefc',
            'edfab',
            'fag',
            'ag',
            'dagbf',
            'cfgbd',
        ],
        output: ['efacgd', 'dbefag', 'fadebg', 'bgfad'],
    },
    {
        input: [
            'bf',
            'fbd',
            'cgbdaf',
            'dcfbae',
            'fgbcd',
            'gcbadef',
            'gafcde',
            'bfag',
            'cebgd',
            'dcafg',
        ],
        output: ['afbedc', 'gcdeb', 'fbgadc', 'dbf'],
    },
    {
        input: [
            'gfecab',
            'fageb',
            'cgb',
            'acgeb',
            'gdfeab',
            'ecbafdg',
            'gfca',
            'aecbd',
            'gc',
            'edcgbf',
        ],
        output: ['afcg', 'cedba', 'aecdb', 'cgeba'],
    },
    {
        input: [
            'cdge',
            'abfdge',
            'cgfeadb',
            'bdc',
            'gbacd',
            'cd',
            'cdaebf',
            'bgeda',
            'cgdaeb',
            'acfgb',
        ],
        output: ['baecdg', 'fcbag', 'dfeagb', 'gcde'],
    },
    {
        input: [
            'efabdgc',
            'ecafg',
            'dacgbf',
            'ecgfd',
            'dfe',
            'gbfdec',
            'ed',
            'bedc',
            'cfdgb',
            'gedafb',
        ],
        output: ['egcaf', 'cfgae', 'efcgd', 'de'],
    },
    {
        input: [
            'bfagdc',
            'dbagef',
            'gbedcf',
            'afdeb',
            'ab',
            'edgfb',
            'gdebfac',
            'fdeca',
            'baf',
            'eagb',
        ],
        output: ['bfa', 'bgadfc', 'adcef', 'ab'],
    },
    {
        input: [
            'cfdbae',
            'dgefc',
            'fcaeg',
            'geafdc',
            'dfag',
            'fd',
            'cegbd',
            'daefbgc',
            'cfd',
            'cefbag',
        ],
        output: ['efgcd', 'cgdfe', 'cefdg', 'cdf'],
    },
    {
        input: [
            'cbged',
            'feabc',
            'fdgb',
            'egf',
            'ecfdbg',
            'dfgcea',
            'gabfdce',
            'ebcdag',
            'bgefc',
            'fg',
        ],
        output: ['fbgec', 'bgdf', 'efgcbda', 'cbedg'],
    },
    {
        input: [
            'ebcdfa',
            'ef',
            'cfe',
            'cadbfge',
            'becfd',
            'dgbeac',
            'dafe',
            'gbdfc',
            'cefgba',
            'ceabd',
        ],
        output: ['bfcaeg', 'gfedcab', 'acbfge', 'fe'],
    },
    {
        input: [
            'fbdage',
            'bf',
            'acdgb',
            'cabf',
            'gcfed',
            'gdcfbea',
            'fgbdc',
            'fbd',
            'fcbadg',
            'bgedca',
        ],
        output: ['bcadeg', 'bf', 'facbdeg', 'gdabef'],
    },
    {
        input: [
            'gfacdbe',
            'fga',
            'gbdaf',
            'gadbc',
            'dfeagc',
            'fg',
            'bcgf',
            'eacgbd',
            'acdgfb',
            'debfa',
        ],
        output: ['gdcab', 'agcbd', 'dafbecg', 'gfa'],
    },
    {
        input: [
            'gadbcf',
            'badfe',
            'bae',
            'cfaed',
            'abfdg',
            'adfecbg',
            'eb',
            'bedgaf',
            'ecfagb',
            'egdb',
        ],
        output: ['bdaef', 'egfdcab', 'eb', 'be'],
    },
    {
        input: [
            'dbgecaf',
            'gacd',
            'dfbac',
            'dbaefg',
            'dba',
            'bfgced',
            'cafbdg',
            'cbfgd',
            'faecb',
            'ad',
        ],
        output: ['degbcf', 'baegdf', 'gaedbf', 'dfegbc'],
    },
    {
        input: [
            'afgcd',
            'dabgf',
            'gedfba',
            'agc',
            'bdfgac',
            'gdefc',
            'bcaf',
            'cfeadgb',
            'ac',
            'ecdbga',
        ],
        output: ['gfadbec', 'fgcda', 'edgbac', 'fbagd'],
    },
    {
        input: [
            'acbegfd',
            'cgeb',
            'dagbef',
            'gbaed',
            'caebdg',
            'gc',
            'dafgec',
            'adcbg',
            'cdbfa',
            'gdc',
        ],
        output: ['bdaeg', 'bdfac', 'bdfac', 'bcgad'],
    },
    {
        input: [
            'gfab',
            'agfbde',
            'fa',
            'edbgf',
            'cbedfa',
            'decga',
            'cdagefb',
            'degbfc',
            'egfda',
            'afd',
        ],
        output: ['daf', 'fa', 'afd', 'efacbd'],
    },
    {
        input: [
            'caegdbf',
            'daefg',
            'fbgac',
            'be',
            'fgaeb',
            'cbea',
            'bge',
            'cdfagb',
            'dgecfb',
            'abecfg',
        ],
        output: ['gebaf', 'aceb', 'gfdecb', 'befga'],
    },
    {
        input: [
            'efcgda',
            'bd',
            'efgdcab',
            'afbec',
            'bgcd',
            'fdagc',
            'dgabef',
            'dab',
            'dafbc',
            'cfdagb',
        ],
        output: ['dba', 'dcgb', 'ecbdfga', 'abfcd'],
    },
    {
        input: [
            'abdge',
            'fd',
            'fda',
            'fecd',
            'bfcage',
            'fecdba',
            'fdgbcea',
            'afbde',
            'acdbfg',
            'cfbea',
        ],
        output: ['fedc', 'fced', 'adebf', 'fbacde'],
    },
    {
        input: [
            'acfdbe',
            'egcadb',
            'gfbacd',
            'acfbd',
            'bagefcd',
            'bgfa',
            'cefgd',
            'gac',
            'cdagf',
            'ag',
        ],
        output: ['ag', 'bcadeg', 'dgcafb', 'cefdg'],
    },
    {
        input: [
            'eabdfc',
            'fcaeg',
            'fecad',
            'bcfda',
            'dcfbge',
            'ebda',
            'de',
            'ced',
            'fdacbg',
            'dfbcega',
        ],
        output: ['gcebfda', 'gdecfba', 'dbgfec', 'defca'],
    },
    {
        input: [
            'bfc',
            'gdfceb',
            'cf',
            'eafgbd',
            'edcab',
            'ebcfa',
            'gfeacb',
            'acgf',
            'adcbgef',
            'fabge',
        ],
        output: ['bafgecd', 'fgabe', 'aegbcf', 'badec'],
    },
    {
        input: [
            'gfbc',
            'gaced',
            'fg',
            'bfcda',
            'fgd',
            'fcgad',
            'dgefbac',
            'bcafde',
            'dgcfab',
            'edgfba',
        ],
        output: ['bcgf', 'bdceaf', 'dbfaec', 'bdacf'],
    },
    {
        input: [
            'acbdgf',
            'dfcgb',
            'dcfeg',
            'egbd',
            'aedfc',
            'fcebag',
            'ge',
            'gef',
            'cfegdba',
            'fgbdce',
        ],
        output: ['gcbfea', 'fceda', 'dcfgb', 'dfgbc'],
    },
    {
        input: [
            'agcfd',
            'fga',
            'fecda',
            'gadebf',
            'dbgcfe',
            'fcbdga',
            'dcfgb',
            'ga',
            'gbac',
            'cbfgead',
        ],
        output: ['fdeca', 'gbcdf', 'cfdgb', 'afg'],
    },
    {
        input: [
            'eba',
            'ebdc',
            'gbefda',
            'dcbegaf',
            'fbaced',
            'afgec',
            'be',
            'dcfba',
            'ebacf',
            'dfcagb',
        ],
        output: ['eb', 'eab', 'bea', 'be'],
    },
    {
        input: [
            'bfcge',
            'bfead',
            'edgfacb',
            'edcfag',
            'abegfd',
            'becdf',
            'dacb',
            'cd',
            'cde',
            'bfdcea',
        ],
        output: ['adefgc', 'cdab', 'fbead', 'dcba'],
    },
    {
        input: [
            'bacegd',
            'gafcbe',
            'begfa',
            'bcfad',
            'ed',
            'gedf',
            'ebgfda',
            'bdefa',
            'ead',
            'fegdbac',
        ],
        output: ['geafb', 'fedba', 'dbcage', 'egdf'],
    },
    {
        input: [
            'df',
            'fbgdc',
            'fcd',
            'bfgce',
            'abfd',
            'cdfgba',
            'cgefad',
            'cgbad',
            'ecadgb',
            'egbfacd',
        ],
        output: ['bcdgaf', 'cedfga', 'dbgafc', 'dgfbc'],
    },
    {
        input: [
            'dfabge',
            'bcfdg',
            'egfbca',
            'bdaefcg',
            'decbfg',
            'ebfgd',
            'fgdca',
            'cb',
            'cbde',
            'cbg',
        ],
        output: ['beadcgf', 'dgacf', 'adfgc', 'bc'],
    },
    {
        input: [
            'fgda',
            'dafecgb',
            'egdbf',
            'gef',
            'dbgec',
            'agebcf',
            'gf',
            'edgafb',
            'fcaedb',
            'bafde',
        ],
        output: ['fg', 'fecdab', 'bdefg', 'bgfde'],
    },
    {
        input: [
            'abfgecd',
            'eabgf',
            'fcdabe',
            'gbdafe',
            'acebg',
            'dfecgb',
            'gf',
            'gfb',
            'fgad',
            'dafeb',
        ],
        output: ['efdacb', 'efadcgb', 'dagf', 'dfabe'],
    },
    {
        input: [
            'ceafbg',
            'dfcabe',
            'gcfea',
            'gbac',
            'fgead',
            'gc',
            'cbdgef',
            'egc',
            'aecfgbd',
            'cefba',
        ],
        output: ['badecf', 'badefgc', 'bfaec', 'cbeaf'],
    },
    {
        input: [
            'cadfb',
            'caefbd',
            'cbfega',
            'fdbga',
            'cad',
            'dc',
            'edbc',
            'aefbc',
            'egbacfd',
            'dfgeca',
        ],
        output: ['cefdab', 'cdfage', 'bacdf', 'dbafc'],
    },
    {
        input: [
            'gfcb',
            'cf',
            'ecafdg',
            'fcbed',
            'dfbagce',
            'fbgeda',
            'gdfbec',
            'cef',
            'eacbd',
            'ebdfg',
        ],
        output: ['gbdaef', 'caedfg', 'cf', 'gbdefc'],
    },
    {
        input: [
            'gd',
            'cgd',
            'ebdafgc',
            'cfbega',
            'gcbfde',
            'bcfdg',
            'badfc',
            'bgaced',
            'bcefg',
            'gedf',
        ],
        output: ['gfed', 'fcbgd', 'cdgfbe', 'cfbeg'],
    },
    {
        input: [
            'bfga',
            'dabge',
            'befacd',
            'agbdce',
            'fb',
            'aegfbd',
            'fcged',
            'dbegf',
            'ebf',
            'ebgdcaf',
        ],
        output: ['bagf', 'ecfdg', 'fbe', 'bedagc'],
    },
    {
        input: [
            'beac',
            'ea',
            'ade',
            'gefcd',
            'ecgbad',
            'cbagd',
            'badgcfe',
            'ebfgad',
            'acgde',
            'gcfdab',
        ],
        output: ['ea', 'gceadb', 'gcbad', 'cbdga'],
    },
    {
        input: [
            'cadfbg',
            'bcgafed',
            'cbedf',
            'afeg',
            'abegdc',
            'adf',
            'gedca',
            'efacd',
            'acdgfe',
            'fa',
        ],
        output: ['daecg', 'fdecga', 'edafc', 'adbgce'],
    },
    {
        input: [
            'egd',
            'ed',
            'egacd',
            'cgabfed',
            'efcd',
            'degfca',
            'dagbfc',
            'dcagf',
            'bgfdea',
            'abecg',
        ],
        output: ['dge', 'egcad', 'ged', 'cgdfa'],
    },
    {
        input: [
            'cgdeaf',
            'fcbdeg',
            'fgc',
            'dgcea',
            'cadgbe',
            'abdcfeg',
            'gf',
            'cafbe',
            'gadf',
            'cfega',
        ],
        output: ['aecgfd', 'bfaec', 'gf', 'dceabg'],
    },
    {
        input: [
            'caegd',
            'cbfgae',
            'dafg',
            'egd',
            'gd',
            'ecafg',
            'gfabdec',
            'cafdge',
            'bacde',
            'bdfecg',
        ],
        output: ['gedfcb', 'edcagfb', 'cdega', 'becgfd'],
    },
    {
        input: [
            'badgfe',
            'ed',
            'dcge',
            'fgdceb',
            'cebfd',
            'cbfedga',
            'dabcf',
            'efd',
            'ecgafb',
            'cgbef',
        ],
        output: ['dgec', 'dfe', 'ecbgfa', 'cebgaf'],
    },
    {
        input: [
            'dgabcef',
            'bcd',
            'cfeadb',
            'degfca',
            'bgace',
            'gcebd',
            'cegfd',
            'gbdf',
            'bd',
            'begfdc',
        ],
        output: ['acbeg', 'dbc', 'gdfb', 'gfdb'],
    },
    {
        input: [
            'edafgb',
            'bagf',
            'acedb',
            'dbg',
            'fcgdabe',
            'bcdgfe',
            'gb',
            'bgead',
            'dfaecg',
            'faged',
        ],
        output: ['gafb', 'dgafeb', 'gbaf', 'fadegb'],
    },
    {
        input: [
            'bc',
            'abcegf',
            'bfcgd',
            'gdcbef',
            'dcbe',
            'gcb',
            'cafegbd',
            'aegdbf',
            'dfagc',
            'dbegf',
        ],
        output: ['cbg', 'cbg', 'cfedgba', 'dgcfabe'],
    },
    {
        input: [
            'be',
            'ecgbf',
            'cbafg',
            'ebg',
            'bagedc',
            'fbae',
            'degfabc',
            'fgcdab',
            'dgfce',
            'cabfeg',
        ],
        output: ['gfcde', 'dgfbca', 'dcabgf', 'bacegd'],
    },
    {
        input: [
            'af',
            'dbacge',
            'efa',
            'abegfdc',
            'gfdce',
            'begcfa',
            'aecfg',
            'afbced',
            'fgba',
            'ecabg',
        ],
        output: ['ecadfb', 'gfeca', 'efa', 'gefdc'],
    },
    {
        input: [
            'acbedg',
            'edfacbg',
            'begd',
            'cdfabe',
            'dagcb',
            'eacdb',
            'gfeabc',
            'bg',
            'gba',
            'dfgac',
        ],
        output: ['cegbaf', 'ecfdba', 'cgbda', 'dfebca'],
    },
    {
        input: [
            'dcbgaef',
            'bca',
            'abed',
            'cbgad',
            'gdaec',
            'fecbag',
            'edgbca',
            'geadfc',
            'ab',
            'cdgfb',
        ],
        output: ['beagcd', 'dgbca', 'eabd', 'ceabgd'],
    },
    {
        input: [
            'cgabe',
            'gfcbe',
            'cfegba',
            'fdbgc',
            'fe',
            'fdgebca',
            'aedcbg',
            'gfea',
            'bfdcea',
            'fbe',
        ],
        output: ['feb', 'gaef', 'badgec', 'ecgabf'],
    },
    {
        input: [
            'afecdg',
            'dfbc',
            'cd',
            'dcg',
            'aegcb',
            'baedgf',
            'becgd',
            'becfdg',
            'eacgbdf',
            'ebdgf',
        ],
        output: ['gbedf', 'edgbf', 'bcdeg', 'gfadbe'],
    },
    {
        input: [
            'gfdba',
            'adbefc',
            'ebcdfag',
            'bcgaf',
            'bfdaeg',
            'dg',
            'adbfe',
            'egbacd',
            'bgd',
            'dfge',
        ],
        output: ['gbd', 'bgd', 'bcgfa', 'fbgad'],
    },
    {
        input: [
            'dfaegb',
            'fe',
            'bcgde',
            'face',
            'afgbdc',
            'acgebdf',
            'agfcb',
            'cgbef',
            'fcgbea',
            'gfe',
        ],
        output: ['acef', 'afedgb', 'bgdfcea', 'fgedab'],
    },
    {
        input: [
            'abdcef',
            'gdfea',
            'cbaef',
            'gaefb',
            'cagebf',
            'agfdbec',
            'agdbfc',
            'ecgb',
            'fbg',
            'bg',
        ],
        output: ['aebfc', 'egcb', 'acfgbe', 'gebc'],
    },
    {
        input: [
            'bcf',
            'gbadec',
            'bf',
            'bgaf',
            'fcdea',
            'cgbda',
            'gebdfc',
            'dgefcab',
            'fcabd',
            'bdagcf',
        ],
        output: ['edacf', 'bf', 'cfb', 'gadcb'],
    },
    {
        input: [
            'cdafgb',
            'bgdf',
            'gacefd',
            'cdb',
            'bd',
            'ecfadbg',
            'cdafg',
            'cdebag',
            'bfadc',
            'ecafb',
        ],
        output: ['bcefa', 'cfdba', 'agdfc', 'fabdc'],
    },
    {
        input: [
            'egb',
            'dgbf',
            'bgdeca',
            'febag',
            'fbadge',
            'ebadf',
            'aecfg',
            'gb',
            'geacfdb',
            'fbacde',
        ],
        output: ['fdbg', 'bg', 'caegf', 'egfab'],
    },
    {
        input: [
            'ac',
            'eagfbdc',
            'bgacf',
            'cbdgae',
            'gabdf',
            'acdf',
            'gdfaeb',
            'acg',
            'dbgafc',
            'gbfce',
        ],
        output: ['gdbeaf', 'agbcf', 'dcbagf', 'fgadeb'],
    },
    {
        input: [
            'ef',
            'eagf',
            'bfegcd',
            'gbaefd',
            'fbe',
            'eafbd',
            'dagfb',
            'abced',
            'agcfbd',
            'abcefdg',
        ],
        output: ['ef', 'ef', 'ecdgfab', 'deafb'],
    },
    {
        input: [
            'fdgbc',
            'efbgd',
            'aedbg',
            'dfce',
            'bcagdf',
            'fe',
            'fegcab',
            'cdgabef',
            'efg',
            'cgdfbe',
        ],
        output: ['efgcdb', 'efg', 'agcfeb', 'dgfabc'],
    },
    {
        input: [
            'fe',
            'dbefgac',
            'baegc',
            'eagfc',
            'ebgf',
            'acdgf',
            'aedbfc',
            'bgafce',
            'cef',
            'bcgdea',
        ],
        output: ['agbdce', 'aecbfg', 'cdgaf', 'ef'],
    },
    {
        input: [
            'fbgcd',
            'bdf',
            'dfbega',
            'dfcga',
            'abfdcg',
            'db',
            'dabc',
            'cfebg',
            'feadgc',
            'ecgbdaf',
        ],
        output: ['fcbeg', 'gcdfb', 'cgbdf', 'acfdg'],
    },
    {
        input: [
            'bac',
            'cdbeagf',
            'abfd',
            'bcfea',
            'edcfba',
            'abdcge',
            'edacf',
            'gcbfe',
            'gcdefa',
            'ba',
        ],
        output: ['cegfb', 'cafde', 'ba', 'fegdcba'],
    },
    {
        input: [
            'gcabfd',
            'acdg',
            'cg',
            'gfdbcae',
            'ecbgfa',
            'cbg',
            'bfegd',
            'gdcfb',
            'cedafb',
            'fadcb',
        ],
        output: ['cgfbd', 'cfgdb', 'fdegb', 'cg'],
    },
    {
        input: [
            'fcdaegb',
            'gdefcb',
            'dgfacb',
            'dcgea',
            'eb',
            'dgcbf',
            'afcegb',
            'bgced',
            'bdef',
            'bec',
        ],
        output: ['ecdag', 'eb', 'befd', 'dabcfge'],
    },
    {
        input: [
            'defcb',
            'eabcf',
            'bca',
            'abfeg',
            'ac',
            'cafbge',
            'gfac',
            'dbaecg',
            'fcbegad',
            'bagedf',
        ],
        output: ['bfgae', 'cfga', 'ecabf', 'aegbcf'],
    },
    {
        input: [
            'gdcfea',
            'adgcf',
            'cbged',
            'bgadfc',
            'gbf',
            'gfdbc',
            'cfegdba',
            'bcfa',
            'bf',
            'dgaefb',
        ],
        output: ['fgadc', 'bfg', 'fb', 'bf'],
    },
    {
        input: [
            'bdgcaef',
            'adg',
            'egbca',
            'cdabg',
            'eadbcg',
            'eadc',
            'cgdfb',
            'efagbd',
            'ad',
            'ebfagc',
        ],
        output: ['da', 'dace', 'dga', 'gedfab'],
    },
    {
        input: [
            'cade',
            'afgecd',
            'fgedc',
            'cbaegf',
            'efbgd',
            'gdfcabe',
            'ce',
            'fec',
            'cadgfb',
            'dcgaf',
        ],
        output: ['ce', 'adefgc', 'cdea', 'fce'],
    },
    {
        input: [
            'efgcba',
            'ged',
            'gcdbea',
            'acgeb',
            'decag',
            'cdgaf',
            'egbcafd',
            'bdae',
            'fgcbed',
            'de',
        ],
        output: ['adeb', 'edg', 'cgadf', 'agdec'],
    },
    {
        input: [
            'agfce',
            'af',
            'febgc',
            'ebgadc',
            'cadeg',
            'dafg',
            'faegcd',
            'bceadf',
            'bfaecgd',
            'efa',
        ],
        output: ['egbcf', 'fbgec', 'acedg', 'af'],
    },
    {
        input: [
            'cbgdae',
            'debcfa',
            'becadfg',
            'agecb',
            'gcde',
            'cfgba',
            'ce',
            'begda',
            'bec',
            'fdaebg',
        ],
        output: ['bec', 'eadgb', 'eadbg', 'badefgc'],
    },
    {
        input: [
            'bagedf',
            'ecf',
            'ec',
            'dbefc',
            'cbedfa',
            'edca',
            'dfbcg',
            'edbfa',
            'eabgfc',
            'aefgcdb',
        ],
        output: ['fec', 'dafebc', 'cfe', 'aefdb'],
    },
    {
        input: [
            'aef',
            'bface',
            'dabefg',
            'ebfdgac',
            'caeg',
            'bgfac',
            'fcegba',
            'fcbed',
            'ae',
            'cfgbad',
        ],
        output: ['efcba', 'baefc', 'afbcg', 'gbcfa'],
    },
    {
        input: [
            'dfeca',
            'fdagcb',
            'feagc',
            'adcbef',
            'fg',
            'gefd',
            'cabge',
            'fgdbace',
            'cegadf',
            'cgf',
        ],
        output: ['fg', 'decfab', 'cfdbga', 'baecg'],
    },
    {
        input: [
            'gbaefd',
            'agedbcf',
            'cagbe',
            'fb',
            'cgbeaf',
            'baefc',
            'bfgc',
            'bgeacd',
            'efb',
            'dcfae',
        ],
        output: ['gcbaed', 'fb', 'bgfcae', 'bcfg'],
    },
    {
        input: [
            'cegf',
            'bcedg',
            'bgacdef',
            'gbedf',
            'fg',
            'ebadf',
            'ebgdcf',
            'dgcfba',
            'debgac',
            'bfg',
        ],
        output: ['bdfgca', 'bgf', 'fgdbce', 'becfadg'],
    },
    {
        input: [
            'decafgb',
            'acgbd',
            'fegdab',
            'cefag',
            'dfcga',
            'gdf',
            'fd',
            'aecfgb',
            'dfecga',
            'cefd',
        ],
        output: ['gcebfa', 'fgacbe', 'fgbdae', 'fcde'],
    },
    {
        input: [
            'faebc',
            'acb',
            'bdfgca',
            'afgedcb',
            'ab',
            'daeb',
            'fcbge',
            'afcebd',
            'feacd',
            'cafedg',
        ],
        output: ['fbgdca', 'ab', 'afedgc', 'ceafbd'],
    },
    {
        input: [
            'gfeb',
            'ebgcdfa',
            'dfgca',
            'abfdg',
            'agebd',
            'bf',
            'abf',
            'bceafd',
            'dabgce',
            'dbfgae',
        ],
        output: ['fgeb', 'gadbf', 'gcafd', 'bf'],
    },
    {
        input: [
            'ecbdfg',
            'gecdfa',
            'efcadgb',
            'ebdac',
            'deabf',
            'fbga',
            'bf',
            'dbf',
            'efagbd',
            'dfgae',
        ],
        output: ['adfbe', 'cfdage', 'efdcga', 'gfab'],
    },
    {
        input: [
            'fg',
            'cedbgaf',
            'feacbd',
            'dafgeb',
            'fag',
            'gfecba',
            'acgde',
            'febac',
            'cfega',
            'fcgb',
        ],
        output: ['decbgfa', 'fg', 'ecgad', 'afdbgce'],
    },
    {
        input: [
            'cfbgde',
            'aegcdf',
            'daefbc',
            'dgceb',
            'fcged',
            'gafdecb',
            'cbfg',
            'bc',
            'ceb',
            'gebad',
        ],
        output: ['dafecbg', 'eagdb', 'bec', 'begdc'],
    },
    {
        input: [
            'cdefga',
            'fbgcade',
            'fgdca',
            'cd',
            'bafdec',
            'adc',
            'dbgeaf',
            'cafgb',
            'efgda',
            'cegd',
        ],
        output: ['afcgb', 'ecdg', 'bcfag', 'caedfg'],
    },
    {
        input: [
            'agfbc',
            'af',
            'deagfbc',
            'fecbg',
            'gfa',
            'fcegbd',
            'cfae',
            'bgafec',
            'edagbf',
            'bcadg',
        ],
        output: ['agf', 'ecfa', 'becfg', 'af'],
    },
    {
        input: [
            'bdgf',
            'afceg',
            'adcfeb',
            'egbaf',
            'afgbde',
            'afb',
            'fb',
            'cegbfda',
            'daebg',
            'adgbec',
        ],
        output: ['fba', 'ceadgbf', 'bf', 'fb'],
    },
    {
        input: [
            'efgb',
            'eg',
            'aecbd',
            'ecbdg',
            'daecgf',
            'dcgfb',
            'fbagdc',
            'egfadcb',
            'gce',
            'ecbgdf',
        ],
        output: ['afbegcd', 'fegdac', 'cebad', 'bgafdc'],
    },
    {
        input: [
            'acgbd',
            'eb',
            'dbace',
            'bdafgc',
            'fabdge',
            'bceg',
            'gecdba',
            'edcaf',
            'aeb',
            'bagcdef',
        ],
        output: ['fdgabc', 'fegadb', 'dgbcfea', 'egabfd'],
    },
    {
        input: [
            'cadfgb',
            'acefdg',
            'fcb',
            'fbea',
            'fb',
            'ebdfca',
            'ebcdf',
            'degcb',
            'dfaec',
            'cbdefga',
        ],
        output: ['aefcdbg', 'cdegaf', 'gdbec', 'dcfae'],
    },
    {
        input: [
            'fcdab',
            'edc',
            'cfeb',
            'gdfcae',
            'dcaeb',
            'ec',
            'gdcbaf',
            'fdcabe',
            'debga',
            'efbgadc',
        ],
        output: ['fcbe', 'gbaed', 'fcaedb', 'acedgf'],
    },
    {
        input: [
            'gb',
            'gefca',
            'acbfge',
            'bdgaecf',
            'bfcag',
            'bdfca',
            'abg',
            'aedfgb',
            'gebc',
            'agfecd',
        ],
        output: ['cgafb', 'ebcg', 'aecfg', 'efgbac'],
    },
    {
        input: [
            'dgabcef',
            'fbdgea',
            'fb',
            'cdbf',
            'cebfg',
            'bdaegc',
            'dgceb',
            'egcdfb',
            'bfg',
            'acgef',
        ],
        output: ['cbgde', 'faegc', 'befgdca', 'cbdf'],
    },
    {
        input: [
            'cfaebdg',
            'fg',
            'fgcead',
            'agedb',
            'fge',
            'ebcdf',
            'gebdf',
            'dfeagb',
            'dbgace',
            'fgab',
        ],
        output: ['gfba', 'eagdfcb', 'dcabeg', 'cegafd'],
    },
    {
        input: [
            'fbe',
            'egcba',
            'bgefdca',
            'bgdafe',
            'afdgb',
            'fdbgac',
            'dgcbfe',
            'fbega',
            'defa',
            'fe',
        ],
        output: ['ebf', 'egafb', 'fbgdac', 'egafb'],
    },
    {
        input: [
            'gdc',
            'acfdeg',
            'geabc',
            'dbfg',
            'dabcfe',
            'dbeafcg',
            'dg',
            'bedcf',
            'edcgb',
            'efcbdg',
        ],
        output: ['agcefd', 'cbdfe', 'dg', 'bcedf'],
    },
    {
        input: [
            'bafgcd',
            'febdgca',
            'abgcf',
            'bcgea',
            'be',
            'edgac',
            'aeb',
            'cbef',
            'afebgd',
            'ecgbfa',
        ],
        output: ['bea', 'eb', 'ecfbag', 'abfcg'],
    },
    {
        input: [
            'cdae',
            'cbd',
            'gacbe',
            'fcbdge',
            'cefbag',
            'bagcde',
            'gcabd',
            'bdafg',
            'dc',
            'fdgebca',
        ],
        output: ['cegdfb', 'gbeacd', 'cd', 'cabdge'],
    },
    {
        input: [
            'dac',
            'dfgae',
            'fcdabg',
            'agbc',
            'dcfbg',
            'gfedbc',
            'fadcg',
            'bfaegcd',
            'ca',
            'eadbcf',
        ],
        output: ['cfabged', 'ac', 'cbag', 'dfceab'],
    },
    {
        input: [
            'egbdcf',
            'bdeagfc',
            'aegcb',
            'bafec',
            'fdceb',
            'edgafc',
            'caebfd',
            'aef',
            'fbad',
            'af',
        ],
        output: ['efa', 'adfcbge', 'dfba', 'ebgac'],
    },
    {
        input: [
            'ebadg',
            'fcaeb',
            'dc',
            'acdg',
            'becgfd',
            'adecgbf',
            'dbc',
            'dbeafg',
            'dbaec',
            'bedagc',
        ],
        output: ['cdb', 'bdc', 'dc', 'aecbd'],
    },
    {
        input: [
            'cfaegbd',
            'agbdce',
            'edca',
            'badgf',
            'edgfbc',
            'ebagd',
            'ed',
            'gde',
            'aebfgc',
            'ebcag',
        ],
        output: ['cbeag', 'edca', 'gdbea', 'fbedgc'],
    },
    {
        input: [
            'fgb',
            'dfagceb',
            'cabgdf',
            'gf',
            'afge',
            'ecbaf',
            'deabcf',
            'cbdeg',
            'bgefc',
            'gfceba',
        ],
        output: ['bgecd', 'gf', 'bacef', 'fg'],
    },
    {
        input: [
            'abd',
            'fgcdaeb',
            'gfeabc',
            'gdfacb',
            'fcbea',
            'faebcd',
            'dcbeg',
            'badce',
            'ad',
            'dafe',
        ],
        output: ['adecb', 'gfaebc', 'fdcbga', 'aecdb'],
    },
    {
        input: [
            'fcgdeab',
            'eabgf',
            'feagd',
            'dge',
            'dg',
            'cdaefb',
            'acedbg',
            'cdfg',
            'gcaedf',
            'efadc',
        ],
        output: ['cfade', 'cbeadg', 'bgfea', 'dg'],
    },
    {
        input: [
            'fegcb',
            'fcedag',
            'badgce',
            'fcbdgea',
            'afg',
            'gafeb',
            'af',
            'dbgefa',
            'degba',
            'fadb',
        ],
        output: ['fbegc', 'fabge', 'af', 'dcgabe'],
    },
    {
        input: [
            'abcdfg',
            'dcbfea',
            'bagd',
            'cegfb',
            'bd',
            'dbf',
            'cgafde',
            'edgcbfa',
            'fgdca',
            'bcdfg',
        ],
        output: ['fdabce', 'gbcfd', 'cbefda', 'ecabdf'],
    },
    {
        input: [
            'afgbd',
            'fbgde',
            'dcfageb',
            'ag',
            'gba',
            'gfdcab',
            'eadgcb',
            'cfag',
            'daebfc',
            'cdbfa',
        ],
        output: ['ga', 'ag', 'bdaefc', 'ga'],
    },
    {
        input: [
            'egf',
            'ecabfd',
            'fg',
            'ecdfb',
            'cfgb',
            'cbegadf',
            'dgbfae',
            'begcfd',
            'agcde',
            'cgdfe',
        ],
        output: ['gbdefa', 'fedgc', 'cafedb', 'cfdge'],
    },
    {
        input: [
            'bafcdge',
            'dgbace',
            'cgbad',
            'cdafe',
            'bedcfg',
            'be',
            'abge',
            'cebad',
            'dcfabg',
            'bed',
        ],
        output: ['dbe', 'gabfced', 'cgbedf', 'cbadg'],
    },
    {
        input: [
            'becagf',
            'fdec',
            'debafc',
            'afedb',
            'adbgc',
            'bgdfea',
            'dabcf',
            'cf',
            'cabegfd',
            'afc',
        ],
        output: ['bagdc', 'decf', 'fca', 'dfbae'],
    },
    {
        input: [
            'dcagb',
            'gfcade',
            'cgdebf',
            'fdbeag',
            'gdfeabc',
            'efdcg',
            'ecfb',
            'deb',
            'egbcd',
            'eb',
        ],
        output: ['eb', 'edagbf', 'ebfc', 'eagdcf'],
    },
    {
        input: [
            'ebcdaf',
            'fgdc',
            'gbeac',
            'dgfae',
            'efadbg',
            'cd',
            'gcefda',
            'dgace',
            'fbgedac',
            'cda',
        ],
        output: ['aegdc', 'dfabge', 'gcade', 'daceg'],
    },
    {
        input: [
            'fgdcb',
            'adceb',
            'fcgeabd',
            'acedbg',
            'af',
            'fba',
            'aebgdf',
            'efac',
            'dcabfe',
            'adbcf',
        ],
        output: ['cdbaf', 'cgeadb', 'bdcae', 'bfgaed'],
    },
    {
        input: [
            'fcb',
            'fc',
            'fcdgb',
            'dabfg',
            'eabcfdg',
            'cbged',
            'cefg',
            'begdca',
            'gcdbfe',
            'efdacb',
        ],
        output: ['ecfg', 'fabgcde', 'gdecbaf', 'bacged'],
    },
    {
        input: [
            'gfdabc',
            'ad',
            'bdfgea',
            'fegbdac',
            'gbaecf',
            'bfega',
            'adg',
            'adbe',
            'afged',
            'egdcf',
        ],
        output: ['dcfgab', 'bgcefa', 'gad', 'gafcbd'],
    },
    {
        input: [
            'bgdcfea',
            'afb',
            'gabfcd',
            'adbfeg',
            'efdba',
            'bgdfe',
            'dfgbce',
            'eafdc',
            'bage',
            'ab',
        ],
        output: ['ab', 'dgefb', 'baf', 'bgaedcf'],
    },
    {
        input: [
            'geabd',
            'adecfgb',
            'cg',
            'ebcdfa',
            'agfbdc',
            'fdcg',
            'dabcf',
            'dcbag',
            'faebcg',
            'cbg',
        ],
        output: ['dagbe', 'fgdbeca', 'cbagdfe', 'fcbeda'],
    },
    {
        input: [
            'bdfa',
            'dafbge',
            'fgedb',
            'bfceg',
            'bdg',
            'afdebgc',
            'bd',
            'bdaecg',
            'defcga',
            'gfdea',
        ],
        output: ['bagfdce', 'dcgafe', 'fegbc', 'dbegca'],
    },
    {
        input: [
            'aedcgb',
            'fb',
            'gdbaf',
            'dgabe',
            'acdfg',
            'fabgde',
            'fadecgb',
            'gbf',
            'edfb',
            'facegb',
        ],
        output: ['agdcf', 'badeg', 'fb', 'fabcge'],
    },
    {
        input: [
            'dfbce',
            'gafed',
            'ba',
            'eagb',
            'gfdbca',
            'aefdb',
            'fecdag',
            'fagbedc',
            'abf',
            'egadfb',
        ],
        output: ['eafdb', 'edfcbag', 'dcfbe', 'ba'],
    },
    {
        input: [
            'afdec',
            'fcegda',
            'edgabc',
            'bgdfc',
            'faebdc',
            'ba',
            'bac',
            'dcfebag',
            'fadbc',
            'fbae',
        ],
        output: ['deafc', 'acb', 'fbgaecd', 'cfdea'],
    },
    {
        input: [
            'gecd',
            'dgf',
            'eabdf',
            'gd',
            'gfdeb',
            'fgcadb',
            'gcbfae',
            'cefbg',
            'cedfbg',
            'cfeabdg',
        ],
        output: ['gd', 'edfba', 'fgbce', 'fbgec'],
    },
    {
        input: [
            'adfge',
            'bcgfde',
            'baecg',
            'dcfgaeb',
            'bafdge',
            'gdeac',
            'dagcef',
            'dc',
            'cdg',
            'acdf',
        ],
        output: ['cgd', 'dgcae', 'gcead', 'cd'],
    },
    {
        input: [
            'efgac',
            'agbfedc',
            'aecbfd',
            'agbfde',
            'dcbg',
            'fdbag',
            'gacdfb',
            'bc',
            'fgbac',
            'fbc',
        ],
        output: ['bc', 'afdegb', 'bgdc', 'edbafg'],
    },
    {
        input: [
            'be',
            'cbfgad',
            'acegdb',
            'agefd',
            'dabgc',
            'cebfgad',
            'gbce',
            'bdega',
            'dfbace',
            'bed',
        ],
        output: ['bagde', 'eb', 'egcb', 'edfbac'],
    },
    {
        input: [
            'gf',
            'fag',
            'afgbe',
            'ecbaf',
            'geadb',
            'eabgdf',
            'egdf',
            'dagbfc',
            'ecagdb',
            'cbgdeaf',
        ],
        output: ['cbefa', 'fg', 'bdega', 'gfacbed'],
    },
    {
        input: [
            'bag',
            'defba',
            'gcfdae',
            'cgbd',
            'gb',
            'eabgfc',
            'gcfabd',
            'dfagb',
            'gcdfa',
            'ecbgfda',
        ],
        output: ['begacf', 'agb', 'cgfade', 'fcdga'],
    },
    {
        input: [
            'adgfcbe',
            'egd',
            'fgadeb',
            'cgbdae',
            'acdgb',
            'cgedb',
            'deca',
            'de',
            'efcbg',
            'acbdgf',
        ],
        output: ['cfbdag', 'dcgba', 'geabdf', 'eadc'],
    },
    {
        input: [
            'cagdebf',
            'dgebcf',
            'edc',
            'abecfd',
            'egfadb',
            'fabed',
            'ec',
            'gadbc',
            'efca',
            'dabce',
        ],
        output: ['dec', 'fbadec', 'debac', 'edc'],
    },
    {
        input: [
            'fcedg',
            'dfgbae',
            'eg',
            'deg',
            'egcb',
            'fgcebd',
            'efacd',
            'gfdcb',
            'gbfecda',
            'gdafbc',
        ],
        output: ['efacd', 'ge', 'cfgabde', 'fagecdb'],
    },
    {
        input: [
            'dbag',
            'aefcbd',
            'gbc',
            'gcdbf',
            'bdcfa',
            'bg',
            'dfabcg',
            'ebadgcf',
            'cfgeba',
            'dgecf',
        ],
        output: ['bfaced', 'gedcf', 'dbag', 'cgbdaf'],
    },
    {
        input: [
            'cdgfbea',
            'gd',
            'bdag',
            'gebca',
            'bdcgfe',
            'dgc',
            'fcagbe',
            'gabedc',
            'afcde',
            'cdaeg',
        ],
        output: ['abgcde', 'ebcga', 'dagb', 'bgcefa'],
    },
    {
        input: [
            'cedgbfa',
            'ecabgd',
            'cdafeb',
            'bafcg',
            'cegdbf',
            'cae',
            'gdae',
            'gabce',
            'ae',
            'edcgb',
        ],
        output: ['aec', 'cageb', 'ecdgfb', 'egda'],
    },
    {
        input: [
            'eacgbf',
            'afbdg',
            'gdecaf',
            'gafbcde',
            'gfc',
            'baefc',
            'bcge',
            'fcabg',
            'fdcbea',
            'cg',
        ],
        output: ['agfdb', 'cgfba', 'bgafc', 'eacgdf'],
    },
    {
        input: [
            'fgebd',
            'fed',
            'bfea',
            'cbdeg',
            'decfga',
            'fe',
            'cfdgba',
            'defbgac',
            'dfgba',
            'afdbeg',
        ],
        output: ['fgdba', 'abegdfc', 'bcadgf', 'fbegd'],
    },
    {
        input: [
            'adbfcg',
            'fagdbe',
            'bagec',
            'dc',
            'fbaedcg',
            'bdfag',
            'gbdca',
            'fcgedb',
            'dcfa',
            'cgd',
        ],
        output: ['fcad', 'bfdgae', 'dgc', 'eagbc'],
    },
    {
        input: [
            'fgbaecd',
            'fgecd',
            'cafeg',
            'feacbg',
            'fdgcb',
            'fgaecd',
            'acdbge',
            'ed',
            'adfe',
            'dge',
        ],
        output: ['cfgdb', 'gcedf', 'deaf', 'cfdbg'],
    },
    {
        input: [
            'gedab',
            'afdcbeg',
            'decabg',
            'bfedcg',
            'dgefab',
            'ef',
            'aedf',
            'cfgab',
            'gbaef',
            'efb',
        ],
        output: ['abcgf', 'cabgf', 'feagdcb', 'cdbaefg'],
    },
    {
        input: [
            'fdb',
            'ebdgfc',
            'bd',
            'adefgcb',
            'efgad',
            'gbcd',
            'dfbge',
            'afcgeb',
            'fecgb',
            'dbeacf',
        ],
        output: ['bfd', 'cgfdeba', 'cafdeb', 'gedfa'],
    },
    {
        input: [
            'abgde',
            'bdefa',
            'fagdbe',
            'fbadceg',
            'dgecab',
            'dfe',
            'ef',
            'edfgca',
            'bfdac',
            'fbge',
        ],
        output: ['fegb', 'cagdeb', 'ecdgab', 'bdagefc'],
    },
    {
        input: [
            'febad',
            'bacged',
            'fge',
            'cdbeg',
            'cfebdag',
            'fgdc',
            'gf',
            'debcgf',
            'bdefg',
            'cfebga',
        ],
        output: ['fg', 'egf', 'beafd', 'efg'],
    },
    {
        input: [
            'agdcbf',
            'bdefcga',
            'cbgefd',
            'dcagb',
            'gbedac',
            'faedc',
            'gfc',
            'bfag',
            'gfcad',
            'gf',
        ],
        output: ['bgfa', 'dbagc', 'bfgdca', 'bcgad'],
    },
    {
        input: [
            'bdce',
            'gafbed',
            'gaecf',
            'bcefdag',
            'gbc',
            'dacbeg',
            'fcbgad',
            'egdab',
            'cb',
            'cegba',
        ],
        output: ['eadbgc', 'cb', 'ebadgf', 'debc'],
    },
    {
        input: [
            'ac',
            'afgceb',
            'eagbf',
            'befcagd',
            'abcg',
            'degcf',
            'aefbdg',
            'ceagf',
            'edbacf',
            'acf',
        ],
        output: ['abecgf', 'bgac', 'gacb', 'ceadbf'],
    },
    {
        input: [
            'abcg',
            'fcaeb',
            'gfdcabe',
            'ab',
            'befdc',
            'cfage',
            'gdbfea',
            'gecdaf',
            'efcgba',
            'bfa',
        ],
        output: ['bgac', 'bcga', 'cagb', 'efgbda'],
    },
    {
        input: [
            'fbdeg',
            'gb',
            'fcdeb',
            'dfecbg',
            'eafgdbc',
            'edgfa',
            'eagbdc',
            'baedfc',
            'cbfg',
            'beg',
        ],
        output: ['adbgce', 'dfcaeb', 'bgfc', 'abcged'],
    },
    {
        input: [
            'afg',
            'afdbec',
            'cbdgaf',
            'afcgedb',
            'bedgf',
            'cdagef',
            'ga',
            'afcdb',
            'gbca',
            'gfbda',
        ],
        output: ['cfagdb', 'edcafg', 'cbfgda', 'bgfed'],
    },
    {
        input: [
            'edgafcb',
            'fdeab',
            'dgabcf',
            'cbgf',
            'gdfeac',
            'dgfab',
            'gdeacb',
            'acgbd',
            'gfa',
            'gf',
        ],
        output: ['gaf', 'bcgf', 'ecbagd', 'agf'],
    },
    {
        input: [
            'dcbfa',
            'gfbace',
            'ebfca',
            'efcg',
            'bgfeadc',
            'abgce',
            'gbafde',
            'ef',
            'beadcg',
            'fbe',
        ],
        output: ['egcf', 'fabdc', 'adebgf', 'bdcage'],
    },
    {
        input: [
            'gc',
            'cfdbe',
            'fgcebd',
            'bcgef',
            'ceg',
            'fdagceb',
            'ecadbg',
            'fgdc',
            'fageb',
            'bedcfa',
        ],
        output: ['adgcbe', 'aefgdcb', 'gabfe', 'gc'],
    },
    {
        input: [
            'fgead',
            'bcdafg',
            'ba',
            'bcae',
            'edafb',
            'bcefad',
            'dbcfe',
            'cafbgde',
            'gbcdef',
            'adb',
        ],
        output: ['dcfeb', 'gecdfb', 'caeb', 'bacdfe'],
    },
    {
        input: [
            'gfeab',
            'abc',
            'bc',
            'ecbf',
            'gdebaf',
            'gebac',
            'gdcea',
            'gecdfba',
            'acdfbg',
            'fbgcae',
        ],
        output: ['cbdagf', 'gbcae', 'bc', 'edgbaf'],
    },
    {
        input: [
            'aecgf',
            'acbf',
            'cgadef',
            'fecbg',
            'bc',
            'ebc',
            'dcegba',
            'befdg',
            'aebgcf',
            'afdebgc',
        ],
        output: ['ecb', 'bcgfe', 'bgedf', 'abcf'],
    },
    {
        input: [
            'fg',
            'facg',
            'efcagd',
            'eadfg',
            'cebfda',
            'feg',
            'daegb',
            'bdfcge',
            'afced',
            'cfeadgb',
        ],
        output: ['acdfe', 'fgeda', 'fg', 'cdbegf'],
    },
    {
        input: [
            'gefda',
            'fed',
            'edfbgc',
            'fgeab',
            'cfad',
            'cdeag',
            'fd',
            'cebgad',
            'dcefabg',
            'fagdce',
        ],
        output: ['faegdc', 'eafdg', 'fd', 'cgbfdea'],
    },
    {
        input: [
            'ebfad',
            'cf',
            'befca',
            'gabedc',
            'fac',
            'cabeg',
            'dcaefg',
            'abfecg',
            'fbacged',
            'gcbf',
        ],
        output: ['bfade', 'fcbg', 'fc', 'cgbf'],
    },
    {
        input: [
            'aegbf',
            'cbdfega',
            'adbfg',
            'ef',
            'cebdgf',
            'dfcbga',
            'gebca',
            'fadgbe',
            'afde',
            'gfe',
        ],
        output: ['fdae', 'afcbgd', 'bgcedaf', 'gef'],
    },
    {
        input: [
            'cdgab',
            'cg',
            'edgbac',
            'gbedfa',
            'gebcdaf',
            'dcebfg',
            'gcd',
            'degba',
            'aceg',
            'dacfb',
        ],
        output: ['gdc', 'cgdba', 'cdg', 'gbadc'],
    },
    {
        input: [
            'daebfg',
            'fcebgad',
            'db',
            'gacbf',
            'feacdg',
            'gafdb',
            'eafdbc',
            'dgaef',
            'dfb',
            'bedg',
        ],
        output: ['cefdbag', 'gedfca', 'gafdeb', 'befcda'],
    },
    {
        input: [
            'ecfd',
            'fcdgba',
            'cebgf',
            'fge',
            'bgafed',
            'febdcg',
            'cbfegad',
            'cabeg',
            'fe',
            'gfdbc',
        ],
        output: ['ecgdfb', 'edfc', 'gebdaf', 'fecd'],
    },
    {
        input: [
            'fac',
            'gbeaf',
            'bcdga',
            'adgbcef',
            'febcda',
            'cfgba',
            'gefbda',
            'bagcfe',
            'cfge',
            'fc',
        ],
        output: ['gcfe', 'gbcaf', 'acfbeg', 'acdgb'],
    },
    {
        input: [
            'afegdcb',
            'fdgba',
            'bfgacd',
            'fdcg',
            'fd',
            'cbfga',
            'adf',
            'ebcagf',
            'dcfabe',
            'gbdae',
        ],
        output: ['df', 'bcaefd', 'cfagb', 'df'],
    },
    {
        input: [
            'cdbgef',
            'bgef',
            'ge',
            'ged',
            'badec',
            'agfdcb',
            'adgecf',
            'cgdeb',
            'cbgdf',
            'fdbceag',
        ],
        output: ['dcfgb', 'gcebd', 'egbf', 'dcegb'],
    },
    {
        input: [
            'dfbea',
            'gb',
            'cfgea',
            'bag',
            'fgbc',
            'debcga',
            'acdbgef',
            'afcgbe',
            'gfeba',
            'cfdaeg',
        ],
        output: ['beafd', 'bag', 'cbgf', 'gba'],
    },
    {
        input: [
            'fdgcab',
            'cd',
            'ebdaf',
            'baecdgf',
            'cda',
            'bcgaf',
            'cfebga',
            'acebgd',
            'cbdaf',
            'cfgd',
        ],
        output: ['aegcfb', 'cdgf', 'cdgf', 'afegbdc'],
    },
    {
        input: [
            'fcbga',
            'cbeagf',
            'dcabg',
            'da',
            'dfabcg',
            'bdaf',
            'begcd',
            'dca',
            'fdagce',
            'bcgfdae',
        ],
        output: ['acgbd', 'dbceg', 'acd', 'cfbga'],
    },
    {
        input: [
            'degacbf',
            'cf',
            'dcgfba',
            'adegbf',
            'efgab',
            'gfce',
            'acfeb',
            'dbeca',
            'caf',
            'gcebaf',
        ],
        output: ['bacfe', 'abfecg', 'ebafc', 'debac'],
    },
    {
        input: [
            'bcaefd',
            'gbce',
            'dcegfb',
            'gcbadf',
            'dgfaecb',
            'fbdce',
            'dgcfe',
            'cg',
            'agfed',
            'fcg',
        ],
        output: ['dbgfec', 'gc', 'acdgfb', 'efbcd'],
    },
    {
        input: [
            'cdfag',
            'dgebacf',
            'bdfagc',
            'fba',
            'acdgef',
            'fcdab',
            'bfdg',
            'baedc',
            'gbfaec',
            'fb',
        ],
        output: ['cedbafg', 'fb', 'dgfeac', 'cadbf'],
    },
    {
        input: [
            'bcdgf',
            'eafcbgd',
            'bd',
            'adfb',
            'dcabeg',
            'gebfac',
            'gcfba',
            'gfdacb',
            'fdgce',
            'bgd',
        ],
        output: ['cfbga', 'fgcab', 'db', 'fcegd'],
    },
    {
        input: [
            'cdgafe',
            'deg',
            'bedfc',
            'dfgb',
            'cgdbe',
            'dg',
            'dcefba',
            'efdgbc',
            'cagbefd',
            'cegab',
        ],
        output: ['bgdf', 'abfdec', 'egd', 'gedbfc'],
    },
    {
        input: [
            'bg',
            'febdca',
            'edgcb',
            'cdeab',
            'gbc',
            'edgbca',
            'gdab',
            'beagcf',
            'cdegf',
            'debacfg',
        ],
        output: ['bcaedf', 'dgcef', 'badg', 'fecadbg'],
    },
    {
        input: [
            'dbca',
            'cgaedb',
            'gcfbe',
            'cea',
            'fadbeg',
            'gabce',
            'ca',
            'edcafg',
            'degab',
            'abfedgc',
        ],
        output: ['fdebag', 'beacg', 'abcd', 'adcegb'],
    },
    {
        input: [
            'gcdfe',
            'adbfgec',
            'cbafge',
            'dgbaf',
            'ebf',
            'gfbced',
            'eb',
            'adcgfe',
            'becd',
            'fgebd',
        ],
        output: ['ecgfba', 'gcbfde', 'dbec', 'cdafge'],
    },
    {
        input: [
            'dbgeafc',
            'dacbg',
            'badfge',
            'abfce',
            'ed',
            'eda',
            'dcfe',
            'decba',
            'dcfeab',
            'gfbeca',
        ],
        output: ['febcda', 'defc', 'beacf', 'fdgabe'],
    },
    {
        input: [
            'efcd',
            'bfcadge',
            'fcdba',
            'egabf',
            'bfdcag',
            'dcefba',
            'deagbc',
            'fabed',
            'ed',
            'edb',
        ],
        output: ['gbeacd', 'fdeab', 'ebcfad', 'fageb'],
    },
    {
        input: [
            'dcgf',
            'fegdab',
            'bcaeg',
            'dcegaf',
            'dga',
            'gd',
            'dcfbea',
            'fcdea',
            'aedcg',
            'bdefgca',
        ],
        output: ['cbegdfa', 'eabcfd', 'adfce', 'cbefda'],
    },
    {
        input: [
            'bf',
            'edfbgc',
            'cegbf',
            'bcadefg',
            'ebf',
            'acbfde',
            'gcedf',
            'feadgc',
            'gbcae',
            'gfbd',
        ],
        output: ['feb', 'dfgb', 'egbcdfa', 'dfegc'],
    },
    {
        input: [
            'efgba',
            'eacd',
            'efadcg',
            'dcgefb',
            'gacdf',
            'dbcfgae',
            'efd',
            'bgcdaf',
            'edfga',
            'ed',
        ],
        output: ['cfbgda', 'dgcfa', 'gcfead', 'eadfg'],
    },
    {
        input: [
            'afgdc',
            'fbg',
            'cdgaef',
            'fagbdc',
            'bgcefa',
            'cdbf',
            'bgdaf',
            'bdaeg',
            'fb',
            'dgabcfe',
        ],
        output: ['dagfc', 'cefagb', 'egcabf', 'fcbd'],
    },
    {
        input: [
            'cadgfe',
            'acbed',
            'cfabgde',
            'fdbcge',
            'cfga',
            'fad',
            'fdeabg',
            'fa',
            'dcaef',
            'dcfge',
        ],
        output: ['fad', 'bafgecd', 'cfegad', 'adbfcge'],
    },
    {
        input: [
            'agdefc',
            'cfad',
            'bdgecfa',
            'gadfe',
            'aefgc',
            'ad',
            'ceadgb',
            'gbafce',
            'bfedg',
            'agd',
        ],
        output: ['dag', 'ad', 'fcage', 'cgbafe'],
    },
];
